name: Daily YouTube Shorts Surfer

on:
  workflow_dispatch:
  schedule:
    - cron: '21 19 * * *'

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Python script
        run: python youtube_surfer.py

      - name: Commit and push log files
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the log file. Use -f to force add if it's in .gitignore
          git add -f automation_log.txt
          
          # Check if an error screenshot exists and add it
          if [ -f "error_screenshot.png" ]; then
            git add error_screenshot.png
          fi
          
          # Commit the changes if there are any changes to commit
          # The `|| exit 0` part prevents the workflow from failing if there's nothing to commit
          git commit -m "Update automation log for $(date)" || exit 0
          
          # Push the changes back to the main branch
          git push